export const municipisCatalunya = [
  'Abella de la Conca',
  'Abrera',
  'Agramunt',
  'Aguilar de Segarra',
  'Agullana',
  'Aiguafreda',
  'Aiguamúrcia',
  'Alella',
  'Alpens',
  'Ametlla del Vallès',
  'Arenys de Mar',
  'Arenys de Munt',
  'Artés',
  'Avià',
  'Avinyó',
  'Avinyonet del Penedès',
  'Badalona',
  'Bagà',
  'Balenyà',
  'Balsareny',
  'Barberà del Vallès',
  'Barcelona',
  'Begues',
  'Bellprat',
  'Berga',
  'Bigues i Riells',
  'Borredà',
  'Bruc',
  'Brull',
  'Cabanyes',
  "Cabrera d'Anoia",
  'Cabrera de Mar',
  'Cabrils',
  'Calaf',
  'Calders',
  'Caldes de Montbui',
  "Caldes d'Estrac",
  'Calella',
  'Calldetenes',
  'Callús',
  'Calonge de Segarra',
  'Campins',
  'Canet de Mar',
  'Canovelles',
  'Cànoves i Samalús',
  'Canyelles',
  'Capellades',
  'Capolat',
  'Cardedeu',
  'Cardona',
  'Carme',
  'Carmel',
  'Casserres',
  'Castellbell i el Vilar',
  "Castellar de n'Hug",
  'Castellar del Riu',
  'Castellar del Vallès',
  'Castellfollit de la Roca',
  'Castellfollit del Boix',
  'Castellgalí',
  'Castellnou de Bages',
  'Castellolí',
  'Castellterçol',
  'Castellví de la Marca',
  'Castellví de Rosanes',
  'Centelles',
  'Cerdanyola del Vallès',
  'Cervelló',
  'Cistella',
  'Collbató',
  'Colldejou',
  'Collsuspina',
  'Conca de Dalt',
  'Conesa',
  'Consell de Cent',
  'Corbera de Llobregat',
  'Cornellà de Llobregat',
  'Corçà',
  'Cubelles',
  'Cunit',
  'Dosrius',
  'Esparreguera',
  'Espinelves',
  'Esplugues de Llobregat',
  'Esponellà',
  'Espolla',
  'Esquirol',
  'Estamariu',
  'Estany',
  'Fígols',
  'Flaçà',
  'Folgueroles',
  'Fonollosa',
  'Fogars de la Selva',
  'Fogars de Montclús',
  'Folgueroles',
  'Fondarella',
  'Fontcoberta',
  'Font-rubí',
  'Gaià',
  'Gavà',
  'Gombrèn',
  'Gualba',
  'Granera',
  'Granollers',
  'Gualta',
  'Gavà Mar',
  'Gavà Centre',
  'Girona',
  'Gironella',
  'Gualta',
  'Guardiola de Berguedà',
  'Guixers',
  'Hospitalet de Llobregat',
  'Igualada',
  'Isona i Conca Dellà',
  'Isòvol',
  'Jorba',
  'Juià',
  "La Bisbal d'Empordà",
  'La Canonja',
  'La Cellera de Ter',
  'La Floresta',
  'La Garriga',
  'La Jonquera',
  'La Llacuna',
  'La Llagosta',
  'La Nou de Berguedà',
  'La Palma de Cervelló',
  'La Pobla de Claramunt',
  'La Pobla de Lillet',
  'La Pobla de Montornès',
  'La Pobla de Segur',
  'La Portella',
  'La Ràpita',
  'La Secuita',
  'La Sentiu de Sió',
  "La Seu d'Urgell",
  'La Torre de Claramunt',
  "La Torre de l'Espanyol",
  'La Vall de Bianya',
  'La Vall de Boí',
  "La Vall d'en Bas",
  "La Vall d'Uixó",
  'La Vallfogona de Balaguer',
  'La Vansa i Fórnols',
  "L'Ametlla de Mar",
  "L'Arboç",
  "L'Aldea",
  "L'Aleixar",
  "L'Albi",
  "L'Albagés",
  "L'Albiol",
  "L'Alcúdia",
  "L'Albiol de la Selva",
  "L'Aldea",
  "L'Albi",
  "L'Ampolla",
  "L'Ametlla del Vallès",
  "L'Areny",
  "L'Armentera",
  "L'Arboç de la Serra",
  "L'Arboç",
  "L'Espluga de Francolí",
  "L'Esquirol",
  "L'Estany",
  'Lladurs',
  'Lladó',
  'Llagostera',
  'Llançà',
  'Llorenç del Penedès',
  'Llorenç',
  'Llívia',
  'Lluçà',
  'Malgrat de Mar',
  'Manlleu',
  'Manresa',
  'Marganell',
  'Masdenverge',
  'Masies de Roda',
  'Masies de Voltregà',
  'Masllorenç',
  'Masnou',
  'Masquefa',
  'Matadepera',
  'Mediona',
  'Mieres',
  'Miravet',
  'Moià',
  'Molins de Rei',
  'Mollet del Vallès',
  'Monistrol de Montserrat',
  'Montblanc',
  'Montcada i Reixac',
  'Montferrer i Castellbò',
  'Montferri',
  'Montmajor',
  'Montmaneu',
  'Montmell',
  'Montoliu de Lleida',
  'Montornès del Vallès',
  'Montseny',
  'Montsia',
  'Montsoriu',
  'Mont-ral',
  'Mont-roig del Camp',
  'Mont-ras',
  'Mont-raser',
  "Móra d'Ebre",
  'Móra la Nova',
  'Muntanyola',
  'Muntanyola del Baix',
  'Navarcles',
  'Navàs',
  'Negre',
  'Nou de Berguedà',
  'Òdena',
  'Olesa de Bonesvalls',
  'Olesa de Montserrat',
  'Oliana',
  'Olost',
  'Olvan',
  'Ordis',
  'Organyà',
  'Oristà',
  'Orpí',
  'Osor',
  'Òssos de Sió',
  'Palafolls',
  'Palamós',
  'Pallejà',
  'Palau-solità i Plegamans',
  'Palau de Anglesola',
  'Palau de Cerdanya',
  'Palau de Santa Eulàlia',
  'Palau de Sant Andreu',
  'Palau de Sant Miquel',
  'Palau de Torelló',
  'Pals',
  'Parlavà',
  'Passanant i Belltall',
  'Pedret i Marzà',
  'Pedret',
  'Pedrera',
  'Peralada',
  'Perafita',
  'Peramola',
  'Peralada',
  'Piera',
  'Piles',
  'Pineda de Mar',
  'Pinós',
  'Pont de Suert',
  'Pontons',
  'Ponts',
  'Porqueres',
  'Prades',
  'Prats de Lluçanès',
  'Prats de Rei',
  'Prat de Llobregat',
  'Premià de Dalt',
  'Premià de Mar',
  'Puigcerdà',
  'Puig-reig',
  'Pujalt',
  'Quart',
  'Queralbs',
  'Quintana de la Serra',
  'Rabós',
  'Ribes de Freser',
  'Ripoll',
  'Riumors',
  'Roda de Ter',
  'Roda de Berà',
  'Roses',
  'Rubí',
  'Rupit i Pruit',
  'Saldes',
  'Salt',
  'Sallent',
  'Sant Adrià de Besòs',
  'Sant Andreu de Llavaneres',
  'Sant Andreu de la Barca',
  'Sant Antoni de Vilamajor',
  'Sant Bartomeu del Grau',
  'Sant Boi de Llobregat',
  'Sant Cebrià de Vallalta',
  'Sant Celoni',
  'Sant Climent de Llobregat',
  'Sant Feliu de Codines',
  'Sant Feliu de Guíxols',
  'Sant Feliu de Llobregat',
  'Sant Fruitós de Bages',
  'Sant Gregori',
  'Sant Hipòlit de Voltregà',
  'Sant Jaume de Frontanyà',
  'Sant Joan de les Abadesses',
  'Sant Joan de Mollet',
  'Sant Joan de Vilatorrada',
  'Sant Joan les Fonts',
  'Sant Julià de Cerdanyola',
  'Sant Julià de Ramis',
  'Sant Just Desvern',
  "Sant Llorenç d'Hortons",
  'Sant Llorenç Savall',
  'Sant Martí de Centelles',
  'Sant Martí de Tous',
  'Sant Martí Sarroca',
  'Sant Martí Vell',
  'Sant Pere de Ribes',
  'Sant Pere de Riudebitlles',
  'Sant Pere de Torelló',
  'Sant Pere de Vilamajor',
  'Sant Pol de Mar',
  'Sant Quirze de Besora',
  'Sant Quirze del Vallès',
  "Sant Sadurní d'Anoia",
  "Sant Sadurní d'Heura",
  'Sant Salvador de Guardiola',
  'Sant Vicenç de Castellet',
  'Sant Vicenç de Montalt',
  'Sant Vicenç de Torelló',
  'Sant Vicenç dels Horts',
  'Santa Coloma de Farners',
  'Santa Coloma de Gramenet',
  'Santa Eugènia de Berga',
  'Santa Eulàlia de Riuprimer',
  'Santa Eulàlia de Ronçana',
  'Santa Fe del Penedès',
  "Santa Llogaia d'Àlguema",
  'Santa Maria de Besora',
  'Santa Maria de Corcó',
  'Santa Maria de Martorelles',
  'Santa Maria de Merlès',
  "Santa Maria d'Oló",
  'Santa Pau',
  'Santa Perpètua de Mogoda',
  'Santa Susanna',
  'Santpedor',
  'Sapello',
  'Sarrià de Ter',
  'Sarroca de Bellera',
  'Sarroca de Lleida',
  'Sarroca de Vallbona',
  'Saus, Camallera i Llampaies',
  'Sitges',
  'Sobremunt',
  'Solsona',
  'Sora',
  'Sorre',
  'Subirats',
  'Susqueda',
  'Talarn',
  'Taradell',
  'Tarroja de Segarra',
  'Tarragona',
  'Tarrega',
  'Tavèrnoles',
  'Teià',
  'Terrassa',
  'Tiana',
  'Tivissa',
  'Torelló',
  'Tornabous',
  'Tortosa',
  'Toses',
  'Torroella de Montgrí',
  'Torroella de Fluvià',
  'Torà',
  'Torredembarra',
  'Torrelavit',
  'Torrefarrera',
  'Torregrossa',
  'Torrelameu',
  'Torres de Segre',
  'Torroella del Montgrí',
  'Tortellà',
  'Torroella de Fluvià',
  'Tossa de Mar',
  'Ulldecona',
  'Ullastrell',
  'Ulldemolins',
  'Ullà',
  'Ullastret',
  'Vacarisses',
  "Vallbona d'Anoia",
  'Vallbona de les Monges',
  'Vallcebre',
  'Vallfogona de Ripollès',
  'Vallfogona de Balaguer',
  'Vallirana',
  'Vallromanes',
  'Vall-llobrega',
  'Valls',
  "Vandellòs i l'Hospitalet de l'Infant",
  'Veciana',
  'Vidrà',
  'Vidreres',
  'Vielha e Mijaran',
  'Vila-sana',
  'Vilabertran',
  'Viladecans',
  'Viladecavalls',
  'Vilafranca del Penedès',
  'Vilalba Sasserra',
  'Vilamalla',
  'Vilamacolum',
  'Vilamalla',
  'Vilana',
  'Vilanova de Meià',
  'Vilanova de Sau',
  'Vilanova de la Barca',
  'Vilanova del Camí',
  'Vilanova i la Geltrú',
  'Vilanova de Prades',
  'Vilaplana',
  'Vilassar de Dalt',
  'Vilassar de Mar',
  'Vilella Baixa',
  'Vilella Alta',
  'Vimbodí i Poblet',
  'Vinaixa',
  'Viver i Serrateix',
  'Xerta',
  'Yebra de Segura',
  'Yunquera de Henares',
  'Yurita',
];
